### ISSUE TITLE
root 6 installation problem

### ISSUE THREAD

**Issue by IoanaCodrina** [remenska/root-conda-recipes#1]
Hi, 

Tried to use the conda installation of root 6, on Ubuntu 14.04. I am getting this error message when I try  "root -b -q":

 *** Break *** bus error
    main()
    known_paths = addusersitepackages(known_paths)
    user_site = getusersitepackages()
    user_base = getuserbase() # this will also set USER_BASE
    USER_BASE = get_config_var('userbase')
    return get_config_vars().get(name)
    _init_posix(_CONFIG_VARS)
    from _sysconfigdata import build_time_vars
    from _sysconfigdata_m import *

All the best,
Ioana

**Comment by remenska** [comment]
Could you do ```conda update --all``` and try again?
Also, could you please paste the output from ```conda list```

**Comment by IoanaCodrina** [comment]
Did the update and did not solve the problem. Can it be a conflict with my  other root installations? 

Here is the output of conda list:

# packages in environment at /home/ioana/src/xenon/anaconda3/envs/testenv:
#
cloog                     0.18.0                        0  
fftw                      3.3.4                         2  
fontconfig                2.11.1                        4  
freetype                  2.5.2                         2  
gcc                       4.8.2                        21  
glibc                     2.12.2                        3  
gmp                       5.1.2                         3  
graphviz                  2.38.0                        4  
gsl                       1.16                          2  
isl                       0.12.2                        2  
jpeg                      8d                            0  
libpng                    1.6.17                        0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         0  
linux-headers             2.6.32                        1  
mpc                       1.0.1                         2  
mpfr                      3.1.2                         2  
ncurses                   5.9                           6  
openssl                   1.0.1k                        1  
pcre                      8.35                          2  
pip                       7.1.2                    py34_0  
python                    3.4.3                         1  
qt                        4.8.7                         1  
readline                  6.2.5                        12  
root                      6.04             py3.4_gcc4.8.2  
setuptools                18.4                     py34_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
tk                        8.5.18                        0  
wheel                     0.26.0                   py34_1  
xz                        5.0.5                         0  
zlib                      1.2.8                         0

**Comment by remenska** [comment]
Strange, it shouldn't be the case that other ROOT installation is in the way. Just in case, can you please post these environment variables also?

```echo $PYTHONPATH ```
```echo $ROOTSYS ```
```echo $LD_LIBRARY_PATH ```


Did you install it in a separate conda environment or in the default one?

I'm only guessing, but let's try first the easier way:

(from within the environment)
```
conda install root=6 --force 
source deactivate 
source activate [your_environment_name]
 ```

If that doesn't work, can you recreate an environment with just:

``` conda create --name=py34root6 root=6 python=3.4 ```

and see if it still produces the same result?
