### ISSUE TITLE
ROOT difficulties with PCRE on SLC6.8

### ISSUE THREAD

**Issue by makagan** [remenska/root-conda-recipes#10]
Thank you for these very nice recipes!

After creating and and activating environment with ROOT, when I try to simply run "root -l" from the command line i get the following error:

$ root -l
[ ... ]/anaconda3/pkgs/root-6.04-py3.4_gcc4.8.2/bin/root.exe: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

I was able to fix the problem by setting the LD_LIBRARY_PATH  to:

export LD_LIBRARY_PATH=[ ... ]/anaconda3/envs/testenv/lib:$LD_LIBRARY_PATH
 

However, is there a way to fix this problem without having to explicitly set the LD_LIBRARY_PATH?

**Comment by remenska** [comment]
Can you tell me some more information about the environment? E.g., what is the output of:

```
which root
```

```
conda list
```

after you activate it, of course?

**Comment by makagan** [comment]
Absolutely.  Sorry, one thing, I switched from anaconda to miniconda, but the problem still persists:

$which root
~/workspace/ML_Setup/miniconda3/envs/testenv/bin/root

$conda list
# packages in environment at [ ... ]/workspace/ML_Setup/miniconda3/envs/testenv:
#
cairo                     1.12.18                       6  
cloog                     0.18.0                        0  
cycler                    0.10.0                   py34_0  
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
glib                      2.43.0                        1  
h5py                      2.6.0               np111py34_2  
harfbuzz                  0.9.39                        1  
hdf5                      1.8.17                        1  
jbig                      2.1                           0  
jpeg                      8d                            1  
Keras                     1.0.7                     <pip>
libffi                    3.2.1                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
matplotlib                1.5.1               np111py34_0  
mkl                       11.3.3                        0  
fftw                      3.3.4                         2    NLeSC
gcc                       4.8.2                        25    NLeSC
glibc                     2.12.2                        3    NLeSC
gmp                       5.1.2                         3    NLeSC
graphviz                  2.38.0                        4    NLeSC
gsl                       1.16                          2    NLeSC
isl                       0.12.2                        2    NLeSC
linux-headers             2.6.32                        1    NLeSC
mpc                       1.0.1                         2    NLeSC
mpfr                      3.1.2                         2    NLeSC
pcre                      8.37                          5    NLeSC
root                      6.04             py3.4_gcc4.8.2    NLeSC
root-numpy                4.4.0            root6.04_py3.4    NLeSC
root_numpy                4.3.0            root6.04_py3.4    NLeSC
root_pandas               python3                nppy34_2    NLeSC
numexpr                   2.6.1               np111py34_0  
numpy                     1.11.1                   py34_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py34_0  
pango                     1.39.0                        1  
pip                       8.1.2                    py34_0  
pixman                    0.32.6                        0  
pyparsing                 2.1.4                    py34_0  
pyqt                      4.11.4                   py34_4  
pytables                  3.2.3.1             np111py34_0  
python                    3.4.5                         0  
python-dateutil           2.5.3                    py34_0  
pytz                      2016.6.1                 py34_0  
PyYAML                    3.11                      <pip>
qt                        4.8.7                         4  
readline                  6.2                           2  
scikit-learn              0.17.1              np111py34_2  
scipy                     0.18.0              np111py34_0  
setuptools                25.1.6                   py34_0  
sip                       4.18                     py34_0  
six                       1.10.0                   py34_0  
sqlite                    3.13.0                        0  
Theano                    0.8.2                     <pip>
tk                        8.5.18                        0  
wheel                     0.29.0                   py34_0  
xz                        5.2.2                         0  
zlib                      1.2.8                         3

**Comment by remenska** [comment]
Hm, I think I understand the problem. For some reason (to be investigated) conda resolves to the default channel's readline, not the NLeSC one anymore.
Please try installing it like this:

```
conda install readline=6.2.5=15
```
and let me know if it solves the problem. Should pick up the nlesc channel version of readline.
I will look into what changed in the meantime.

There is another ongoing issue (https://github.com/remenska/root-conda-recipes/issues/9) as a result of conda changing their minds about standard environment variables. This could also be the source of your error, but it's difficult to say.

```
source $CONDA_PREFIX/bin/thisroot.sh
```
should properly set $ROOTSYS.

In any case, LD_LIBRARY_PATH should not be the conda way to go.
Thanks for reporting!

**Comment by makagan** [comment]
Thank you!

I tried:

source $CONDA_PREFIX/bin/thisroot.sh

and indeed that fixed the issue.


I also tried: 

conda install readline=6.2.5=15

in my activated environment.  However, I aborted the the install as it required downgrading several libraries and the python version.  The output from the install was:

The following packages will be DOWNGRADED due to dependency conflicts:

    libtiff:  4.0.6-2       --> 4.0.6-1        (soft-link)
    python:   3.4.5-0       --> 3.4.4-0        (soft-link)
    xz:       5.2.2-0       --> 5.0.5-1        (soft-link)




I will proceed using "source $CONDA_PREFIX/bin/thisroot.sh"

Thank you very much for your help.

**Comment by remenska** [comment]
Great to hear, thanks!

P.S. The downgrade shouldn't break anything, it's not critical ;)

**Comment by makagan** [comment]
Thank you very much!  I decided to try to other method you mentioned, i.e. using 

conda install readline=6.2.5=15

so I could let you know if it works.  Unfortunately it did not seem to fix the problem

**Comment by remenska** [comment]
Thanks for letting me know! The more permanent fix with CONDA_PREFIX is on the way.

**Comment by remenska** [comment]
You no longer need that workaround, new binaries are uploaded, just update your local environment and let me know. :)

**Comment by makagan** [comment]
Sorry, it took me a bit of time to come back to this.  I tried again but still seem to have the same problem.  Specifically, I removed the conda env  and the NLeSC channel and started over.  I proceeded with:

conda config --add channels https://conda.anaconda.org/NLeSC

conda create --name=testenv root=6 python=3 mkl numpy scipy matplotlib scikit-learn h5py root-numpy pandas root_pandas  

source activate testenv

when I run ROOT, I get the same error as before:
[...]/miniconda3/pkgs/root-6.04-py3.4_gcc4.8.2/bin/root.exe: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

Is there something I need to do to get the fix you put in place?

**Comment by remenska** [comment]
That's odd, Travis tests pass without problems.
Conda sometimes tries to play too smart and just uses the cached ROOT binary you probably have somewhere deep in the miniconda directory. It shouldn't (unless the build-number hasn't changed, at least that's how it used to be)

What happens if you activate the environment, and force the new binary to be downloaded:

```
$ conda install root=6 --force
```

Is it of any help?

**Comment by makagan** [comment]
Unfortunately not,  I still have the same problem after the forced install

**Comment by makagan** [comment]
Following up on this, it seems to be dependent on the cluster.  I was able to get everything working smoothly on different cluster, while the trouble I am having (as described above) seem to only appear on the CERN lxplus cluster.  Perhaps you have seen this before?

**Comment by remenska** [comment]
Unfortunately I have no access to lxplus for quite some time now, but I'm surprised the "fix" didn't cut it. After you activate, is ROOTSYS at least properly set? Does `~/anaconda/envs/testenv/lib$ ls | grep pcre` show `libpcre.so.1` ? Is there maybe LD_LIBRARY_PATH set? (which should NOT be, but maybe the login scripts at lxplus set it)

**Comment by makagan** [comment]
Yes, it looks like ROOTSYS is set properly to: [...]/miniconda3/envs/testenv

and        ~/anaconda/envs/testenv/lib$ ls | grep pcre  shows:

libpcre.a
libpcrecpp.a
libpcrecpp.la
libpcrecpp.so
libpcrecpp.so.0
libpcrecpp.so.0.0.1
libpcre.la
libpcreposix.a
libpcreposix.la
libpcreposix.so
libpcreposix.so.0
libpcreposix.so.0.0.3
libpcre.so
libpcre.so.1
libpcre.so.1.2.5

LD_LIBRARY_PATH  does not seem to be set

**Comment by makagan** [comment]
I asked a colleague to try this as well, and they ran into the same issue on lxplus.  Any additional ideas would be welcome, as at this point we are stuck sourcing the root setup every time we activate the env

**Comment by remenska** [comment]
There must be some conflict with an existing ROOT installation. I will try to get an access to lxplus and debug closer what's happening, very soon. Right now, I'm out of additional ideas, sorry :-/  It has been installed on many different cluster setups, but I have never seen this reported.
