### ISSUE TITLE
Request: Root update

### ISSUE THREAD

**Issue by henryiii** [remenska/root-conda-recipes#4]
Is it possible to upgrade to ROOT 6.06? That version has new support for jupyter notebooks. Thanks!

Python 3.5 would be nice, too.

**Comment by remenska** [comment]
ROOT 6.06 is available in the ```dev``` channel (for now, until tested properly)

```conda install -c https://conda.anaconda.org/nlesc/channel/dev root=6.06 ```

Python 3.5 is also coming.

**Comment by henryiii** [comment]
Awesome, thanks!
